fcitx5-skk
fcitx-contrib/fcitx5-macos-plugins pull request #12
Opened 2024-01-07 06:37 UTC by ksqsf

2024-01-07 10:58 UTC, ksqsf commented on patches/skk-XDG_DATA_DIR.patch
Maybe I should submit it to the upstream.

2024-01-07 10:58 UTC, ksqsf commented on scripts/skk.sh
> +f5m_configure -DENABLE_QT=OFF
There is an option `SKK_DEFAULT_PATH` defaulting to `/usr/share`, but it is merely a default path used in the Add Dict dialog, but the GUI config tool is not enabled by our build.

Ideally, the default path should be `~/Library/fcitx5/share/skk-dict/...`, but that requires code changes.

2024-01-07 18:50 UTC, eagleoflqj requested changes
<img width="985" alt="Screenshot 2024-01-07 at 1 47 32 PM" src="https://github.com/fcitx-contrib/fcitx5-macos-plugins/assets/26783539/14a7aad6-5d9f-4b08-967f-70d787e9f25f">

The plugin and main program are downloaded from CI.
I guess your local version works because it loads something from /tmp/fcitx5? Could you please remove that dir and retest?

2024-01-07 18:54 UTC, eagleoflqj commented
Also I'm not able to build it locally.
```
CMake Error in src/CMakeLists.txt:
  Imported target "PkgConfig::GObject2" includes non-existent path

    "/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/ffi"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```

2024-01-08 03:22 UTC, ksqsf commented
Reproduced. I'll try to solve it soon.

> ```
>   Imported target "PkgConfig::GObject2" includes non-existent path
> 
>     "/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/ffi"
> ```

You may need to reinstall `pkg-config`. It seems to hardcode MacOS SDK path.

2024-01-08 22:18 UTC, eagleoflqj approved these changes
This is huge considering dependencies. Great job!

2024-01-08 22:18 UTC, merged